# Generated by Django 2.0.7 on 2018-08-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewClients', models.CharField(max_length=10)),
                ('TotalSales', models.CharField(max_length=10)),
                ('TodayProfit', models.CharField(max_length=10)),
                ('NewInvoice', models.CharField(max_length=10)),
            ],
        ),
    ]
